services:
    sto_content.navbar_menu_builder:
        class: Sto\ContentBundle\Builder\MenuBuilder
        scope: request
        arguments: ['@knp_menu.factory']
        calls:
            - [setSecurityContext, [@security.context]]

    sto_content.navbar_main_menu:
        class: Knp\Menu\MenuItem
        factory_service: sto_content.navbar_menu_builder
        factory_method: createMainMenu
        arguments: ['@request', '@translator']
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }

    sto_content.navbar_right_menu:
        class: Knp\Menu\MenuItem
        factory_service: sto_content.navbar_menu_builder
        factory_method: createRightSideDropdownMenu
        arguments: ['@request', '@translator']
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }

    sto_content.registration.form.type:
        class: Sto\ContentBundle\Form\RegistrationType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: sto_contentbundle_registration }

    sto_content.city.choice_listener:
        class: Sto\ContentBundle\EventListener\ChoiceCityListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    twig.localizeddate:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
