#Sto/UserBundle/Resources/services.yml
parameters:
    my_user_provider.class: Sto\UserBundle\Security\Core\User\FOSUBUserProvider

services:
    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager, @doctrine.orm.entity_manager, {vkontakte: vkontakteId}, %mail_vk_register%]
