services:
    app.admin.deal:
          class: Sto\CoreBundle\Admin\DealAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Акции, label: Акции}
          arguments: [null, Sto\CoreBundle\Entity\Deal, SonataAdminBundle:CRUD]

    app.admin.mark:
          class: Sto\CoreBundle\Admin\MarkAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Автокаталог, label: Марки}
          arguments: [null, Sto\CoreBundle\Entity\Mark, SonataAdminBundle:CRUD]

    app.admin.model:
          class: Sto\CoreBundle\Admin\ModelAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Автокаталог, label: Модели}
          arguments: [null, Sto\CoreBundle\Entity\Model, SonataAdminBundle:CRUD]

    app.admin.modification:
          class: Sto\CoreBundle\Admin\ModificationAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Автокаталог, label: Модификации}
          arguments: [null, Sto\CoreBundle\Entity\Modification, SonataAdminBundle:CRUD]

    app.admin.company:
        class: Sto\CoreBundle\Admin\CompanyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Компании, label: Компании}
        arguments: [null, Sto\CoreBundle\Entity\Company, SonataAdminBundle:CRUD]
        calls: 
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]

    app.admin.company_gallery:
          class: Sto\CoreBundle\Admin\CompanyGalleryAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Компании, label: Галерея}
          arguments: [null, Sto\CoreBundle\Entity\CompanyGallery, SonataAdminBundle:CRUD]

    app.admin.company_manager:
          class: Sto\CoreBundle\Admin\CompanyManagerAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Компании, label: Менеджеры}
          arguments: [null, Sto\CoreBundle\Entity\CompanyManager, SonataAdminBundle:CRUD]

    app.admin.company.company_contacts:
          class: Sto\CoreBundle\Admin\CompanyContactsAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Компании, label: Контакты, show_in_dashboard: false}
          arguments: [null, Sto\CoreBundle\Entity\CompanyContacts, SonataAdminBundle:CRUD]

    app.admin.company.company_phones:
        class: Sto\CoreBundle\Admin\CompanyPhonesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Компании, label: Контакты, show_in_dashboard: false}
        arguments: [null, Sto\CoreBundle\Entity\CompanyPhone, SonataAdminBundle:CRUD]

    app.admin.company.company_emails:
        class: Sto\CoreBundle\Admin\CompanyEmailsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Компании, label: Контакты, show_in_dashboard: false}
        arguments: [null, Sto\CoreBundle\Entity\CompanyEmail, SonataAdminBundle:CRUD]

    app.admin.company.company_specialization:
          class: Sto\CoreBundle\Admin\CompanySpecializationAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Компании, label: Специализация, show_in_dashboard: false}
          arguments: [null, Sto\CoreBundle\Entity\CompanySpecialization, SonataAdminBundle:CRUD]

    app.admin.company.company_service:
          class: Sto\CoreBundle\Admin\CompanyAutoServiceAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Компании, label: Услуги, show_in_dashboard: false}
          arguments: [null, Sto\CoreBundle\Entity\CompanyAutoService, SonataAdminBundle:CRUD]

    app.admin.company.company_working_time:
          class: Sto\CoreBundle\Admin\CompanyWorkingTimeAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Компании, label: Время работы, show_in_dashboard: false}
          arguments: [null, Sto\CoreBundle\Entity\CompanyWorkingTime, SonataAdminBundle:CRUD]

    app.admin.feedback_company:
          class: Sto\CoreBundle\Admin\FeedbackCompanyAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Отзывы, label: Отзывы о компаниях}
          arguments: [null, Sto\CoreBundle\Entity\FeedbackCompany, SonataAdminBundle:CRUD]

    app.admin.feedback_deal:
          class: Sto\CoreBundle\Admin\FeedbackDealAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Отзывы, label: Отзывы об акциях}
          arguments: [null, Sto\CoreBundle\Entity\FeedbackDeal, SonataAdminBundle:CRUD]

    app.admin.feedback_answer:
          class: Sto\CoreBundle\Admin\FeedbackAnswerAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Отзывы, label: Ответы на отзывы}
          arguments: [null, Sto\CoreBundle\Entity\FeedbackAnswer, SonataAdminBundle:CRUD]

    app.admin.rating_points:
          class: Sto\CoreBundle\Admin\RatingPointsAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Отзывы, label: Настройка показателей рейтинга}
          arguments: [null, Sto\CoreBundle\Entity\RatingPoints, SonataAdminBundle:CRUD]

    app.admin.additional_service:
          class: Sto\CoreBundle\Admin\Dictionary\AdditionalServiceAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Справочники, label: Дополнительные услуги}
          arguments: [null, Sto\CoreBundle\Entity\Dictionary\AdditionalService, SonataAdminBundle:CRUD]

    app.admin.auto_service:
          class: Sto\CoreBundle\Admin\AutoServiceAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Справочники, label: Перечень услуг}
          arguments: [null, Sto\CoreBundle\Entity\AutoServices, SonataAdminBundle:CRUD]

    app.admin.company_type:
          class: Sto\CoreBundle\Admin\CompanyTypeAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Справочники, label: Типы организаций}
          arguments: [null, Sto\CoreBundle\Entity\CompanyType, SonataAdminBundle:CRUD]

    app.admin.contact_type:
          class: Sto\CoreBundle\Admin\Dictionary\ContactTypeAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Справочники, label: Типы контактов}
          arguments: [null, Sto\CoreBundle\Entity\Dictionary\ContactType, SonataAdminBundle:CRUD]

    app.admin.country:
          class: Sto\CoreBundle\Admin\CountryAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Справочники, label: Страны / Города}
          arguments: [null, Sto\CoreBundle\Entity\Country, SonataAdminBundle:CRUD]

    app.admin.currency:
          class: Sto\CoreBundle\Admin\Dictionary\CurrencyAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Справочники, label: Валюты}
          arguments: [null, Sto\CoreBundle\Entity\Dictionary\Currency, SonataAdminBundle:CRUD]

    app.admin.deals_type:
          class: Sto\CoreBundle\Admin\DealTypeAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Справочники, label: Типы акций}
          arguments: [null, Sto\CoreBundle\Entity\DealType, SonataAdminBundle:CRUD]

    app.admin.price_level:
          class: Sto\CoreBundle\Admin\Dictionary\PriceLevelAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Справочники, label: Уровни цен}
          arguments: [null, Sto\CoreBundle\Entity\Dictionary\PriceLevel, SonataAdminBundle:CRUD]

    app.admin.work:
          class: Sto\CoreBundle\Admin\Dictionary\WorkAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Справочники, label: Действия / работы}
          arguments: [null, Sto\CoreBundle\Entity\Dictionary\Work, SonataAdminBundle:CRUD]

    app.admin.user.group:
          class: Sto\UserBundle\Admin\GroupAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Пользователи, label: Группы}
          arguments: [null, Sto\UserBundle\Entity\Group, SonataAdminBundle:CRUD]

    app.admin.user.rating_group:
          class: Sto\UserBundle\Admin\RatingGroupAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Пользователи, label: Группы рейтинга}
          arguments: [null, Sto\UserBundle\Entity\RatingGroup, SonataAdminBundle:CRUD]

    app.admin.user.user_gallery:
          class: Sto\UserBundle\Admin\UserGalleryAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Пользователи, label: Галерея}
          arguments: [null, Sto\UserBundle\Entity\UserGallery, SonataAdminBundle:CRUD]

    app.admin.user.user_email:
          class: Sto\CoreBundle\Admin\UserEmailAdmin
          tags:
              - {name: sonata.admin, manager_type: orm, group: Пользователи, label: Список email }
          arguments: [null, Sto\UserBundle\Entity\User, SonataAdminBundle:CRUD]

    app.admin.user.user:
          class: Sto\UserBundle\Admin\UserAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Пользователи, label: Пользователи}
          arguments: [null, Sto\UserBundle\Entity\User, SonataAdminBundle:CRUD]

    app.admin.user.user_contacts:
          class: Sto\UserBundle\Admin\UserContactsAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Пользователи, label: Контакты, show_in_dashboard: false}
          arguments: [null, Sto\UserBundle\Entity\UserContacts, SonataAdminBundle:CRUD]

    sto_core.admin.email_templates:
            class: Sto\CoreBundle\Admin\EmailTemplateAdmin
            arguments: [~, Sto\CoreBundle\Entity\EmailTemplate, SonataAdminBundle:CRUD]
            tags:
                - {name: sonata.admin, manager_type: orm, group: Справочники, label: Шаблоны писем}