services:
    app.admin.deal:
          class: Sto\CoreBundle\Admin\DealAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Акции, label: Акции}
          arguments: [null, Sto\CoreBundle\Entity\Deal, SonataAdminBundle:CRUD]

    app.admin.company:
          class: Sto\CoreBundle\Admin\CompanyAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Компании, label: Компании}
          arguments: [null, Sto\CoreBundle\Entity\Company, SonataAdminBundle:CRUD]

    app.admin.mark:
          class: Sto\CoreBundle\Admin\Catalog\MarkAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Автокаталог, label: Марки}
          arguments: [null, Sto\CoreBundle\Entity\Catalog\Mark, SonataAdminBundle:CRUD]

    app.admin.model:
          class: Sto\CoreBundle\Admin\Catalog\ModelAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Автокаталог, label: Модели}
          arguments: [null, Sto\CoreBundle\Entity\Catalog\Model, SonataAdminBundle:CRUD]

    app.admin.modification:
          class: Sto\CoreBundle\Admin\Catalog\ModificationAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: Автокаталог, label: Модификации}
          arguments: [null, Sto\CoreBundle\Entity\Catalog\Modification, SonataAdminBundle:CRUD]