imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Deprecated in 2.0; will be removed in 2.3 (used trusted_proxies instead)
    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        pagination_default_value: "%pagination_default_value%"
        storage_path: "%storage_path%"

# Assetic Configuration
# assetic:
#     debug:          "%kernel.debug%"
#     use_controller: false
#     bundles:        [ ]
#     #java: /usr/bin/java
#     filters:
#         cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        #

assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    #bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to: "\.less$"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection:   default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            # auto_catalog:
            #     driver:   "%database_second_driver%"
            #     host:     "%database_second_host%"
            #     port:     "%database_second_port%"
            #     dbname:   "%database_second_name%"
            #     user:     "%database_second_user%"
            #     password: "%database_second_password%"
            #     charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        # default_entity_manager:   default
        # entity_managers:
        #     default:
        #         connection:       default
        #         # mapping:    StoUserBundle
        #         #mapping: StoCoreBundle
        #         #mapping: StoAdminBundle
        #     auto_catalog:
        #         connection:       auto_catalog
                #mapping: StoAdminBundle


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Sto\UserBundle\Entity\User

mopa_bootstrap:
    form:
        show_legend: false # default is true
        show_child_legend: false # default is true
        error_type: block # or inline which is default

knp_paginator:
    page_range: 10
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: StoAdminBundle:Pagination:sliding.html.twig

vich_uploader:
    db_driver: orm # or mongodb
    mappings:
        country_image:
            uri_prefix: /images/country
            upload_destination: %kernel.root_dir%/../web/%storage_path%/countries
            delete_on_remove:  true
            namer: vich_uploader.namer_uniqid
            delete_on_update: true
        country_icon:
            uri_prefix: /%storage_path%/countries
            upload_destination: %kernel.root_dir%/../web/%storage_path%/countries
            delete_on_remove:  true
            namer: vich_uploader.namer_uniqid
            delete_on_update: true
        city_image:
            uri_prefix: /images/city
            upload_destination: %kernel.root_dir%/../web/%storage_path%/cities
            delete_on_remove:  true
            namer: vich_uploader.namer_uniqid
            delete_on_update: true
        city_icon:
            uri_prefix: /%storage_path%/cities
            upload_destination: %kernel.root_dir%/../web/%storage_path%/cities
            delete_on_remove:  true
            namer: vich_uploader.namer_uniqid
            delete_on_update: true

# nelmo api config enabled
nelmio_api_doc: ~
