imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: admin_services.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'], assets_version: v5 } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        save_path: null

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        pagination_default_value: "%pagination_default_value%"
        storage_path: "%storage_path%"
    form:
        resources:
            - ShtumiUsefulBundle::fields.html.twig

assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    #bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to: "\.less$"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection:   default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        dql:
            string_functions:
                CONCAT_WS: DoctrineExtensions\Query\Mysql\ConcatWs
            datetime_functions:
                STR_TO_DATE: DoctrineExtensions\Query\Mysql\StrToDate

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Sto\UserBundle\Entity\User
    from_email:
        address: noreply@best4car.ru
        sender_name: Администсрация портала best4car.ru
    group:
        group_class: Sto\UserBundle\Entity\Group
    profile:
        form:
            type: sto_contentbundle_userprofile
    registration:
        form:
            type: sto_contentbundle_registration
    resetting:
        token_ttl: 7200
        email:
            template:   StoUserBundle:Resetting:email.html.twig
    service:
        mailer: fos_user.mailer.twig_swift

knp_menu:
    twig:
        template: StoContentBundle::menu.html.twig


vich_uploader:
    db_driver: orm # or mongodb
    twig: true
    gaufrette: false # set to true to enable gaufrette support
    storage: vich_uploader.storage.file_system
    mappings:
        country_image:
            uri_prefix: /%storage_path%/countries
            upload_destination: %kernel.root_dir%/../web/%storage_path%/countries
            namer: vich_uploader.namer_uniqid
            delete_on_remove:  true
            delete_on_update: true
        country_icon:
            uri_prefix: /%storage_path%/countries
            upload_destination: %kernel.root_dir%/../web/%storage_path%/countries
            namer: vich_uploader.namer_uniqid
            delete_on_remove:  true
            delete_on_update: true
        company_type_icon:
            uri_prefix: /%storage_path%/company_icon
            upload_destination: %kernel.root_dir%/../web/%storage_path%/company_icon
            namer: vich_uploader.namer_uniqid
            delete_on_remove: true
            delete_on_update: true
        user_photo:
            uri_prefix: /%storage_path%/user_photo
            upload_destination: %kernel.root_dir%/../web/%storage_path%/user_photo
            namer: vich_uploader.namer_uniqid
            delete_on_remove: true
            delete_on_update: true
        company_logo:
            uri_prefix: /%storage_path%/company_logo
            upload_destination: %kernel.root_dir%/../web/%storage_path%/company_logo
            namer: vich_uploader.namer_uniqid
            delete_on_remove: true
            delete_on_update: true
        deal_image:
            uri_prefix: /%storage_path%/deal_image
            upload_destination: %kernel.root_dir%/../web/%storage_path%/deal_image
            delete_on_remove:  true
            namer: vich_uploader.namer_uniqid
            delete_on_update: true
        deal_image2:
            uri_prefix: /%storage_path%/deal_image
            upload_destination: %kernel.root_dir%/../web/%storage_path%/deal_image
            delete_on_remove:  true
            namer: vich_uploader.namer_uniqid
            delete_on_update: true
        deal_image3:
            uri_prefix: /%storage_path%/deal_image
            upload_destination: %kernel.root_dir%/../web/%storage_path%/deal_image
            delete_on_remove:  true
            namer: vich_uploader.namer_uniqid
            delete_on_update: true
        company_gallery:
            uri_prefix: /%storage_path%/company/company_gallery
            upload_destination: %kernel.root_dir%/../web/%storage_path%/company/company_gallery
            delete_on_remove: true
            delete_on_update: true
            namer: vich_uploader.namer_uniqid
        catalog_icons:
            uri_prefix: /%storage_path%/catalog/icons
            upload_destination: %kernel.root_dir%/../web/%storage_path%/catalog/icons
            delete_on_remove: true
            delete_on_update: true
            namer: vich_uploader.namer_uniqid
        user_gallery:
            uri_prefix: /%storage_path%/user/gallery
            upload_destination: %kernel.root_dir%/../web/%storage_path%/user/gallery
            delete_on_remove: true
            delete_on_update: true
            namer: vich_uploader.namer_uniqid

nelmio_api_doc: ~

jms_security_extra:
    secure_all_services: true

liip_imagine:
    cache_prefix: /%storage_path%/cache
    filter_sets:
        admin_thumbnails:
            quality: 100
            filters:
                thumbnail: { size: [60, 60], mode: outbound }
        admin_thumbnails_big:
            quality: 100
            filters:
                thumbnail: { size: [640, 480], mode: outbound }
        company_logo_filter:
            quality: 100
            filters:
                relative_resize: { widen: 120 }
        company_logo_card_filter:
            quality: 100
            filters:
                thumbnail: { size: [44, 44], mode: inset }
        user_photo_filter:
            quality: 100
            filters:
                relative_resize: { widen: 120 }
        user_login_avatar:
            quality: 100
            filters:
                thumbnail: { size: [45, 45], mode: outbound }
        service_icon:
            quality: 100
            filters:
                thumbnail: { size: [34, 40], mode: outbound }
        additional_service_icon:
            quality: 100
            filters:
                thumbnail: { size: [24, 28], mode: outbound }
        deals_carusel_photos:
            quality: 100
            filters:
                thumbnail: { size: [500, 279], mode: outbound }
        deals_photos:
            quality: 100
            filters:
                thumbnail: { size: [320, 179], mode: outbound }
        company_logo:
            quality: 100
            filters:
                thumbnail: { size: [52, 52], mode: inset }
        company_gallery_filter:
            quality: 100
            filters:
                thumbnail: { size: [500, 279], mode: outbound }
        deal_filter:
            quality: 100
            filters:
                relative_resize: { widen: 120 }
        dictionary_icon:
            quality: 100
            filters:
                relative_resize: { widen: 70 }
        dictionary_image:
            quality: 100
            filters:
                relative_resize: { widen: 100 }
        dictionary_icon_map:
            quality: 100
            filters:
                relative_resize: { widen: 70 }
        dictionary_icon_small:
            quality: 100
            filters:
                relative_resize: { widen: 100 }
        dictionary_icon_large:
            quality: 100
            filters:
                relative_resize: { widen: 200 }
        contacts_photos:
            quality: 100
            filters:
                thumbnail: { size: [191, 258], mode: outbound }

genemu_form:
    tinymce:
        enabled: true
        theme:   modern
        configs:
            paste_as_text: true
            paste_remove_styles: true
            paste_strip_class_attributes: all
            paste_auto_cleanup_on_paste: true
            valid_elements: "a[href|target],strong,ul,ol,li,em,img[src|width|height|alt],span[style]"
            valid_styles:
                - "span": "text-decoration"

gregwar_captcha:
    width:  200
    height: 50
    length: 5
    as_url: true
    image_folder: %storage_path%/captcha

hwi_oauth:
    resource_owners:
        vkontakte:
            type:          vkontakte
            client_id:     %vk_client_id%
            client_secret: %vk_client_secret%
            scope:         "offline, email"
    firewall_name: main
    fosub:
        username_iterations: 30
        properties:
            vkontakte: vkontakteId
    connect: ~
    http_client:
        timeout:       5
        verify_peer:   true
        ignore_errors: true
        max_redirects: 5

knp_time: ~

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.search_result:
            contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:

sonata_admin:
    title: Sto Admin
    options:
        confirm_exit: false
    templates:
        layout:  StoCoreBundle:Admin:layout.html.twig

services:
    sto.twig.sto_extension:
        class: Sto\CoreBundle\Twig\StoExtension
        tags:
            - { name: twig.extension }

    sto_user.profile.form.type:
        class: Sto\ContentBundle\Form\UserProfileType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: sto_contentbundle_userprofile }

    sto.core.validator.companymanager:
        class: Sto\CoreBundle\Validator\Constraints\CompanyManagerValidator
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: validator.constraint_validator, alias: company_manager_validator }

mannew_hipchat:
    auth_token: 04496c58222155241da099df61acc4

evercode_hipchat_monolog:
    name: Diarrhea

shtumi_useful:
    dependent_filtered_entities:
        subType_by_type:
            class: StoCoreBundle:CompanyType
            parent_property: parent
            property: name
            no_result_msg: ' '
    autocomplete_entities:
        company:
            class: StoCoreBundle:Company
            property: name
