sto_admin:
    resource: "@StoAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin/

sto_content:
    resource: "@StoContentBundle/Controller/"
    type:     annotation
    prefix:   /

sto_core:
    resource: "@StoCoreBundle/Controller/"
    type:     annotation
    prefix:   /

sto_user:
    resource: "@StoUserBundle/Resources/config/routing.yml"
    prefix:   /

sto_user2:
    resource: "@StoUserBundle/Controller"
    type:     annotation
    prefix:   /

_imagine:
    resource: .
    type:     imagine

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix: /login

hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

vkontakte_login:
    pattern: /login/check-vkontakte

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /sonata

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /sonata