sto_user:
    resource: "@StoUserBundle/Resources/config/routing.yml"
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc


root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /companies
        permanent: true

sto_admin:
    resource: "@StoAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin/

sto_content:
    resource: "@StoContentBundle/Controller/"
    type:     annotation
    prefix:   /

sto_core:
    resource: "@StoCoreBundle/Controller/"
    type:     annotation
    prefix:   /

_imagine:
    resource: .
    type:     imagine
