jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
            #vk login username_email
            #id: fos_user.user_manager

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                # added for vk login
                login_path: /login
                check_path: /login_check
                # eof vk login
            logout:       true
            anonymous:    true
            # vk login
            oauth:
                resource_owners:
                    vkontakte: "/login/check-vkontakte"
                login_path: /login
                failure_path: /login
                default_target_path: user-vk-accounting
                # FOSUB integration
                #oauth_user_provider:
                    #service: hwi_oauth.user.provider.fosub_bridge
                oauth_user_provider:
                    service: my_user_provider

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

    #role_hierarchy:
    #    ROLE_REDACTOR:    ROLE_USER
    #    ROLE_MODERATOR:   ROLE_USER
    #    ROLE_ADMIN:       ROLE_MODERATOR
    #    ROLE_SUPER_ADMIN: ROLE_ADMIN
