services:
    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
    sto.company.manager_voter:
        class: Sto\CoreBundle\Service\Voter\CompanyManagerVoter
        public: true
        calls:
            - [setEntityManager, [@doctrine.orm.entity_manager]]
        tags: 
            - { name: security.voter }