services:
    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
    sto.company.manager_voter:
        class: Sto\CoreBundle\Service\Voter\CompanyManagerVoter
        public: true
        calls:
            - [setEntityManager, [@doctrine.orm.entity_manager]]
        tags: 
            - { name: security.voter }
    sto.deal.manager_voter:
        class: Sto\CoreBundle\Service\Voter\DealManagerVoter
        public: true
        calls:
            - [setEntityManager, [@doctrine.orm.entity_manager]]
        tags: 
            - { name: security.voter }
    sto.template_transformer.email:
        class: Sto\CoreBundle\Service\EmailTemplateTransformer
    sto.notifications.email:
        class: Sto\CoreBundle\Service\EmailNotifications
        arguments: [@mailer, @doctrine.orm.entity_manager, @sto.template_transformer.email, @router]
