<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130910152107 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE company_specializations (id INT AUTO_INCREMENT NOT NULL, company_id INT DEFAULT NULL, type_id INT DEFAULT NULL, subType_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_F906A4C2979B1AD6 (company_id), UNIQUE INDEX UNIQ_F906A4C2C54C8C93 (type_id), UNIQUE INDEX UNIQ_F906A4C241931DC0 (subType_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE company_specializations ADD CONSTRAINT FK_F906A4C2979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id)");
        $this->addSql("ALTER TABLE company_specializations ADD CONSTRAINT FK_F906A4C2C54C8C93 FOREIGN KEY (type_id) REFERENCES company_types (id)");
        $this->addSql("ALTER TABLE company_specializations ADD CONSTRAINT FK_F906A4C241931DC0 FOREIGN KEY (subType_id) REFERENCES company_types (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE company_specializations");
    }
}
