<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130626112751 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE auto_catalog (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, uri VARCHAR(255) DEFAULT NULL, visible TINYINT(1) NOT NULL, discr VARCHAR(255) NOT NULL, icon_name VARCHAR(255) DEFAULT NULL, updated_at DATETIME DEFAULT NULL, number_of_doors INT DEFAULT NULL, engine INT DEFAULT NULL, power INT DEFAULT NULL, full_speed INT DEFAULT NULL, body_type VARCHAR(255) DEFAULT NULL, start_of_production VARCHAR(255) DEFAULT NULL, closing_of_production VARCHAR(255) DEFAULT NULL, INDEX IDX_31697F7D727ACA70 (parent_id), INDEX AUTO_CATALOG_NAME_IDX (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE companies (id INT AUTO_INCREMENT NOT NULL, currency_id INT DEFAULT NULL, city_id INT NOT NULL, name VARCHAR(255) NOT NULL, slogan VARCHAR(255) DEFAULT NULL, full_name VARCHAR(255) DEFAULT NULL, web VARCHAR(255) DEFAULT NULL, logo VARCHAR(255) DEFAULT NULL, working_time LONGTEXT NOT NULL COMMENT '(DC2Type:array)', phones LONGTEXT NOT NULL COMMENT '(DC2Type:array)', skype VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, address VARCHAR(255) NOT NULL, gps VARCHAR(255) DEFAULT NULL, createt_date DATE NOT NULL, photos VARCHAR(255) DEFAULT NULL, social_networks VARCHAR(255) DEFAULT NULL, rating DOUBLE PRECISION DEFAULT NULL, reviews VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, subscribable TINYINT(1) NOT NULL, hour_price VARCHAR(255) DEFAULT NULL, administrator_contact_info VARCHAR(255) DEFAULT NULL, visible TINYINT(1) NOT NULL, notes VARCHAR(255) DEFAULT NULL, updated_at DATETIME DEFAULT NULL, vk_link VARCHAR(255) DEFAULT NULL, twitter_link VARCHAR(255) DEFAULT NULL, fb_link VARCHAR(255) DEFAULT NULL, INDEX IDX_8244AA3A38248176 (currency_id), INDEX IDX_8244AA3A8BAC62AF (city_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE company_dictionary_company_type_parrent (company_id INT NOT NULL, dictionary_id INT NOT NULL, INDEX IDX_61B17979B1AD6 (company_id), INDEX IDX_61B17AF5E5B3C (dictionary_id), PRIMARY KEY(company_id, dictionary_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE company_dictionary_company_type_children (company_id INT NOT NULL, dictionary_id INT NOT NULL, INDEX IDX_D4EF96CF979B1AD6 (company_id), INDEX IDX_D4EF96CFAF5E5B3C (dictionary_id), PRIMARY KEY(company_id, dictionary_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE company_additional_service (company_id INT NOT NULL, dictionary_id INT NOT NULL, INDEX IDX_532DAE99979B1AD6 (company_id), INDEX IDX_532DAE99AF5E5B3C (dictionary_id), PRIMARY KEY(company_id, dictionary_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE company_auto_service (company_id INT NOT NULL, dictionary_id INT NOT NULL, INDEX IDX_35151D26979B1AD6 (company_id), INDEX IDX_35151D26AF5E5B3C (dictionary_id), PRIMARY KEY(company_id, dictionary_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE company_group_relationship (company_id INT NOT NULL, group_id INT NOT NULL, INDEX IDX_7F78E926979B1AD6 (company_id), INDEX IDX_7F78E926FE54D947 (group_id), PRIMARY KEY(company_id, group_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE company_autos (auto_id INT NOT NULL, company_id INT NOT NULL, INDEX IDX_1F1CC491D55B925 (auto_id), INDEX IDX_1F1CC49979B1AD6 (company_id), PRIMARY KEY(auto_id, company_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE company_gallery (id INT AUTO_INCREMENT NOT NULL, company_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, image VARCHAR(255) DEFAULT NULL, visible TINYINT(1) NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_677962ED979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE company_manager (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, company_id INT NOT NULL, phone VARCHAR(255) NOT NULL, INDEX IDX_DA763F6EA76ED395 (user_id), INDEX IDX_DA763F6E979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE deals (id INT AUTO_INCREMENT NOT NULL, company_id INT NOT NULL, type_id INT NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, image_name VARCHAR(255) DEFAULT NULL, image_name2 VARCHAR(255) DEFAULT NULL, image_name3 VARCHAR(255) DEFAULT NULL, terms VARCHAR(255) DEFAULT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, start_time TIME NOT NULL, end_time TIME NOT NULL, place VARCHAR(255) DEFAULT NULL, gps VARCHAR(255) DEFAULT NULL, contact_information VARCHAR(255) DEFAULT NULL, updated_at DATETIME DEFAULT NULL, draft TINYINT(1) NOT NULL, INDEX IDX_EF39849B979B1AD6 (company_id), INDEX IDX_EF39849BC54C8C93 (type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE deals_services (services_id INT NOT NULL, deal_id INT NOT NULL, INDEX IDX_18AABA1CAEF5A6C1 (services_id), INDEX IDX_18AABA1CF60E2305 (deal_id), PRIMARY KEY(services_id, deal_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE deals_auto (auto_id INT NOT NULL, deal_id INT NOT NULL, INDEX IDX_D2E53B01D55B925 (auto_id), INDEX IDX_D2E53B0F60E2305 (deal_id), PRIMARY KEY(auto_id, deal_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE deal_auto_service (deal_id INT NOT NULL, dictionary_id INT NOT NULL, INDEX IDX_4900A221F60E2305 (deal_id), INDEX IDX_4900A221AF5E5B3C (dictionary_id), PRIMARY KEY(deal_id, dictionary_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE dictionaries (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, short_name VARCHAR(5) DEFAULT NULL, name VARCHAR(255) NOT NULL, position INT DEFAULT NULL, discr VARCHAR(255) NOT NULL, icon_name_map VARCHAR(255) DEFAULT NULL, icon_name_small VARCHAR(255) DEFAULT NULL, icon_name_large VARCHAR(255) DEFAULT NULL, updated_at DATETIME DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, icon_name VARCHAR(255) DEFAULT NULL, image_name VARCHAR(255) DEFAULT NULL, gps VARCHAR(255) DEFAULT NULL, prefix VARCHAR(255) DEFAULT NULL, code VARCHAR(255) DEFAULT NULL, INDEX IDX_9FC78498727ACA70 (parent_id), INDEX DICTIONARY_NAME_IDX (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE company_autoservices (company_id INT NOT NULL, autoservices_id INT NOT NULL, INDEX IDX_D3F287E0979B1AD6 (company_id), INDEX IDX_D3F287E0A723B282 (autoservices_id), PRIMARY KEY(company_id, autoservices_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE additionalservice_company (additionalservice_id INT NOT NULL, company_id INT NOT NULL, INDEX IDX_1B33B941CFCAAEA6 (additionalservice_id), INDEX IDX_1B33B941979B1AD6 (company_id), PRIMARY KEY(additionalservice_id, company_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE work_deal (work_id INT NOT NULL, deal_id INT NOT NULL, INDEX IDX_1A3D702EBB3453DB (work_id), INDEX IDX_1A3D702EF60E2305 (deal_id), PRIMARY KEY(work_id, deal_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE company_type_auto_service (auto_service_id INT NOT NULL, company_type_id INT NOT NULL, INDEX IDX_1006FC1587C14DDD (auto_service_id), INDEX IDX_1006FC15E51E9644 (company_type_id), PRIMARY KEY(auto_service_id, company_type_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE autoservices_company (autoservices_id INT NOT NULL, company_id INT NOT NULL, INDEX IDX_3EAAD222A723B282 (autoservices_id), INDEX IDX_3EAAD222979B1AD6 (company_id), PRIMARY KEY(autoservices_id, company_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE autoservices_deal (autoservices_id INT NOT NULL, deal_id INT NOT NULL, INDEX IDX_A64958CAA723B282 (autoservices_id), INDEX IDX_A64958CAF60E2305 (deal_id), PRIMARY KEY(autoservices_id, deal_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE feedbacks (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, price_level_id INT DEFAULT NULL, company_id INT DEFAULT NULL, deal_id INT DEFAULT NULL, content LONGTEXT NOT NULL, visit_dates DATE NOT NULL, master_name VARCHAR(255) DEFAULT NULL, car VARCHAR(255) DEFAULT NULL, state_number VARCHAR(255) DEFAULT NULL, order_number VARCHAR(255) DEFAULT NULL, feedback_rating DOUBLE PRECISION NOT NULL, pluses INT NOT NULL, minuses INT NOT NULL, target_rating VARCHAR(255) DEFAULT NULL, published TINYINT(1) NOT NULL, date_feedback DATETIME NOT NULL, ip VARCHAR(255) DEFAULT NULL, is_complain TINYINT(1) DEFAULT NULL, is_hidden TINYINT(1) DEFAULT NULL, discr VARCHAR(255) NOT NULL, company_rating INT DEFAULT NULL, deal_rating INT DEFAULT NULL, INDEX IDX_7E6C3F89A76ED395 (user_id), INDEX IDX_7E6C3F893D0770B0 (price_level_id), INDEX IDX_7E6C3F89979B1AD6 (company_id), INDEX IDX_7E6C3F89F60E2305 (deal_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE feedback_answers (id INT AUTO_INCREMENT NOT NULL, owner_id INT NOT NULL, feedback_id INT NOT NULL, answer LONGTEXT NOT NULL, date DATETIME NOT NULL, is_complain TINYINT(1) DEFAULT NULL, is_hidden TINYINT(1) DEFAULT NULL, INDEX IDX_C189E6A57E3C61F9 (owner_id), UNIQUE INDEX UNIQ_C189E6A5D249A887 (feedback_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE feedback_evaluations (id INT AUTO_INCREMENT NOT NULL, feedback_id INT DEFAULT NULL, user_id INT DEFAULT NULL, review TINYINT(1) NOT NULL, INDEX IDX_B090DCD9D249A887 (feedback_id), INDEX IDX_B090DCD9A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE rating_points (id INT AUTO_INCREMENT NOT NULL, point_name VARCHAR(50) NOT NULL, description VARCHAR(255) NOT NULL, value DOUBLE PRECISION NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE user_contacts (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, company_id INT DEFAULT NULL, type_id INT DEFAULT NULL, value VARCHAR(255) NOT NULL, INDEX IDX_D3CDF173A76ED395 (user_id), INDEX IDX_D3CDF173979B1AD6 (company_id), INDEX IDX_D3CDF173C54C8C93 (type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE groups (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', UNIQUE INDEX UNIQ_F06D39705E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE rating_group (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, min_rating INT NOT NULL, max_rating INT NOT NULL, multiplier INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE users (id INT AUTO_INCREMENT NOT NULL, rating_group_id INT DEFAULT NULL, city_id INT DEFAULT NULL, username VARCHAR(255) NOT NULL, username_canonical VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, email_canonical VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, locked TINYINT(1) NOT NULL, expired TINYINT(1) NOT NULL, expires_at DATETIME DEFAULT NULL, confirmation_token VARCHAR(255) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', credentials_expired TINYINT(1) NOT NULL, credentials_expire_at DATETIME DEFAULT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) DEFAULT NULL, rating INT DEFAULT NULL, rating_bonus INT DEFAULT NULL, phone_number VARCHAR(255) DEFAULT NULL, avatar_url VARCHAR(255) DEFAULT NULL, birth_date DATE DEFAULT NULL, gender VARCHAR(255) DEFAULT NULL, link_vk VARCHAR(255) DEFAULT NULL, vk_id VARCHAR(255) DEFAULT NULL, vk_access_token VARCHAR(255) DEFAULT NULL, link_fb VARCHAR(255) DEFAULT NULL, link_gp VARCHAR(255) DEFAULT NULL, auto_profiles_links VARCHAR(255) DEFAULT NULL, link_garage VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, subscriptions VARCHAR(255) DEFAULT NULL, requests VARCHAR(255) DEFAULT NULL, updated_at DATETIME DEFAULT NULL, using_email TINYINT(1) NOT NULL, avatar_vk VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_1483A5E992FC23A8 (username_canonical), UNIQUE INDEX UNIQ_1483A5E9A0D96FBF (email_canonical), INDEX IDX_1483A5E9A0696CB0 (rating_group_id), INDEX IDX_1483A5E98BAC62AF (city_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE fos_user_user_group (user_id INT NOT NULL, group_id INT NOT NULL, INDEX IDX_B3C77447A76ED395 (user_id), INDEX IDX_B3C77447FE54D947 (group_id), PRIMARY KEY(user_id, group_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE user_gallery (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, image VARCHAR(255) DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_1F266630A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE auto_catalog ADD CONSTRAINT FK_31697F7D727ACA70 FOREIGN KEY (parent_id) REFERENCES auto_catalog (id)");
        $this->addSql("ALTER TABLE companies ADD CONSTRAINT FK_8244AA3A38248176 FOREIGN KEY (currency_id) REFERENCES dictionaries (id)");
        $this->addSql("ALTER TABLE companies ADD CONSTRAINT FK_8244AA3A8BAC62AF FOREIGN KEY (city_id) REFERENCES dictionaries (id)");
        $this->addSql("ALTER TABLE company_dictionary_company_type_parrent ADD CONSTRAINT FK_61B17979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id)");
        $this->addSql("ALTER TABLE company_dictionary_company_type_parrent ADD CONSTRAINT FK_61B17AF5E5B3C FOREIGN KEY (dictionary_id) REFERENCES dictionaries (id)");
        $this->addSql("ALTER TABLE company_dictionary_company_type_children ADD CONSTRAINT FK_D4EF96CF979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id)");
        $this->addSql("ALTER TABLE company_dictionary_company_type_children ADD CONSTRAINT FK_D4EF96CFAF5E5B3C FOREIGN KEY (dictionary_id) REFERENCES dictionaries (id)");
        $this->addSql("ALTER TABLE company_additional_service ADD CONSTRAINT FK_532DAE99979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id)");
        $this->addSql("ALTER TABLE company_additional_service ADD CONSTRAINT FK_532DAE99AF5E5B3C FOREIGN KEY (dictionary_id) REFERENCES dictionaries (id)");
        $this->addSql("ALTER TABLE company_auto_service ADD CONSTRAINT FK_35151D26979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id)");
        $this->addSql("ALTER TABLE company_auto_service ADD CONSTRAINT FK_35151D26AF5E5B3C FOREIGN KEY (dictionary_id) REFERENCES dictionaries (id)");
        $this->addSql("ALTER TABLE company_group_relationship ADD CONSTRAINT FK_7F78E926979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id)");
        $this->addSql("ALTER TABLE company_group_relationship ADD CONSTRAINT FK_7F78E926FE54D947 FOREIGN KEY (group_id) REFERENCES groups (id)");
        $this->addSql("ALTER TABLE company_autos ADD CONSTRAINT FK_1F1CC491D55B925 FOREIGN KEY (auto_id) REFERENCES companies (id)");
        $this->addSql("ALTER TABLE company_autos ADD CONSTRAINT FK_1F1CC49979B1AD6 FOREIGN KEY (company_id) REFERENCES auto_catalog (id)");
        $this->addSql("ALTER TABLE company_gallery ADD CONSTRAINT FK_677962ED979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id)");
        $this->addSql("ALTER TABLE company_manager ADD CONSTRAINT FK_DA763F6EA76ED395 FOREIGN KEY (user_id) REFERENCES users (id)");
        $this->addSql("ALTER TABLE company_manager ADD CONSTRAINT FK_DA763F6E979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id)");
        $this->addSql("ALTER TABLE deals ADD CONSTRAINT FK_EF39849B979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id)");
        $this->addSql("ALTER TABLE deals ADD CONSTRAINT FK_EF39849BC54C8C93 FOREIGN KEY (type_id) REFERENCES dictionaries (id)");
        $this->addSql("ALTER TABLE deals_services ADD CONSTRAINT FK_18AABA1CAEF5A6C1 FOREIGN KEY (services_id) REFERENCES deals (id)");
        $this->addSql("ALTER TABLE deals_services ADD CONSTRAINT FK_18AABA1CF60E2305 FOREIGN KEY (deal_id) REFERENCES dictionaries (id)");
        $this->addSql("ALTER TABLE deals_auto ADD CONSTRAINT FK_D2E53B01D55B925 FOREIGN KEY (auto_id) REFERENCES deals (id)");
        $this->addSql("ALTER TABLE deals_auto ADD CONSTRAINT FK_D2E53B0F60E2305 FOREIGN KEY (deal_id) REFERENCES auto_catalog (id)");
        $this->addSql("ALTER TABLE deal_auto_service ADD CONSTRAINT FK_4900A221F60E2305 FOREIGN KEY (deal_id) REFERENCES deals (id)");
        $this->addSql("ALTER TABLE deal_auto_service ADD CONSTRAINT FK_4900A221AF5E5B3C FOREIGN KEY (dictionary_id) REFERENCES dictionaries (id)");
        $this->addSql("ALTER TABLE dictionaries ADD CONSTRAINT FK_9FC78498727ACA70 FOREIGN KEY (parent_id) REFERENCES dictionaries (id)");
        $this->addSql("ALTER TABLE company_autoservices ADD CONSTRAINT FK_D3F287E0979B1AD6 FOREIGN KEY (company_id) REFERENCES dictionaries (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE company_autoservices ADD CONSTRAINT FK_D3F287E0A723B282 FOREIGN KEY (autoservices_id) REFERENCES dictionaries (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE additionalservice_company ADD CONSTRAINT FK_1B33B941CFCAAEA6 FOREIGN KEY (additionalservice_id) REFERENCES dictionaries (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE additionalservice_company ADD CONSTRAINT FK_1B33B941979B1AD6 FOREIGN KEY (company_id) REFERENCES dictionaries (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE work_deal ADD CONSTRAINT FK_1A3D702EBB3453DB FOREIGN KEY (work_id) REFERENCES dictionaries (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE work_deal ADD CONSTRAINT FK_1A3D702EF60E2305 FOREIGN KEY (deal_id) REFERENCES deals (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE company_type_auto_service ADD CONSTRAINT FK_1006FC1587C14DDD FOREIGN KEY (auto_service_id) REFERENCES dictionaries (id)");
        $this->addSql("ALTER TABLE company_type_auto_service ADD CONSTRAINT FK_1006FC15E51E9644 FOREIGN KEY (company_type_id) REFERENCES dictionaries (id)");
        $this->addSql("ALTER TABLE autoservices_company ADD CONSTRAINT FK_3EAAD222A723B282 FOREIGN KEY (autoservices_id) REFERENCES dictionaries (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE autoservices_company ADD CONSTRAINT FK_3EAAD222979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE autoservices_deal ADD CONSTRAINT FK_A64958CAA723B282 FOREIGN KEY (autoservices_id) REFERENCES dictionaries (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE autoservices_deal ADD CONSTRAINT FK_A64958CAF60E2305 FOREIGN KEY (deal_id) REFERENCES deals (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE feedbacks ADD CONSTRAINT FK_7E6C3F89A76ED395 FOREIGN KEY (user_id) REFERENCES users (id)");
        $this->addSql("ALTER TABLE feedbacks ADD CONSTRAINT FK_7E6C3F893D0770B0 FOREIGN KEY (price_level_id) REFERENCES dictionaries (id)");
        $this->addSql("ALTER TABLE feedbacks ADD CONSTRAINT FK_7E6C3F89979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id)");
        $this->addSql("ALTER TABLE feedbacks ADD CONSTRAINT FK_7E6C3F89F60E2305 FOREIGN KEY (deal_id) REFERENCES deals (id)");
        $this->addSql("ALTER TABLE feedback_answers ADD CONSTRAINT FK_C189E6A57E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id)");
        $this->addSql("ALTER TABLE feedback_answers ADD CONSTRAINT FK_C189E6A5D249A887 FOREIGN KEY (feedback_id) REFERENCES feedbacks (id)");
        $this->addSql("ALTER TABLE feedback_evaluations ADD CONSTRAINT FK_B090DCD9D249A887 FOREIGN KEY (feedback_id) REFERENCES feedbacks (id)");
        $this->addSql("ALTER TABLE feedback_evaluations ADD CONSTRAINT FK_B090DCD9A76ED395 FOREIGN KEY (user_id) REFERENCES users (id)");
        $this->addSql("ALTER TABLE user_contacts ADD CONSTRAINT FK_D3CDF173A76ED395 FOREIGN KEY (user_id) REFERENCES users (id)");
        $this->addSql("ALTER TABLE user_contacts ADD CONSTRAINT FK_D3CDF173979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id)");
        $this->addSql("ALTER TABLE user_contacts ADD CONSTRAINT FK_D3CDF173C54C8C93 FOREIGN KEY (type_id) REFERENCES dictionaries (id)");
        $this->addSql("ALTER TABLE users ADD CONSTRAINT FK_1483A5E9A0696CB0 FOREIGN KEY (rating_group_id) REFERENCES rating_group (id)");
        $this->addSql("ALTER TABLE users ADD CONSTRAINT FK_1483A5E98BAC62AF FOREIGN KEY (city_id) REFERENCES dictionaries (id)");
        $this->addSql("ALTER TABLE fos_user_user_group ADD CONSTRAINT FK_B3C77447A76ED395 FOREIGN KEY (user_id) REFERENCES users (id)");
        $this->addSql("ALTER TABLE fos_user_user_group ADD CONSTRAINT FK_B3C77447FE54D947 FOREIGN KEY (group_id) REFERENCES groups (id)");
        $this->addSql("ALTER TABLE user_gallery ADD CONSTRAINT FK_1F266630A76ED395 FOREIGN KEY (user_id) REFERENCES users (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE auto_catalog DROP FOREIGN KEY FK_31697F7D727ACA70");
        $this->addSql("ALTER TABLE company_autos DROP FOREIGN KEY FK_1F1CC49979B1AD6");
        $this->addSql("ALTER TABLE deals_auto DROP FOREIGN KEY FK_D2E53B0F60E2305");
        $this->addSql("ALTER TABLE company_dictionary_company_type_parrent DROP FOREIGN KEY FK_61B17979B1AD6");
        $this->addSql("ALTER TABLE company_dictionary_company_type_children DROP FOREIGN KEY FK_D4EF96CF979B1AD6");
        $this->addSql("ALTER TABLE company_additional_service DROP FOREIGN KEY FK_532DAE99979B1AD6");
        $this->addSql("ALTER TABLE company_auto_service DROP FOREIGN KEY FK_35151D26979B1AD6");
        $this->addSql("ALTER TABLE company_group_relationship DROP FOREIGN KEY FK_7F78E926979B1AD6");
        $this->addSql("ALTER TABLE company_autos DROP FOREIGN KEY FK_1F1CC491D55B925");
        $this->addSql("ALTER TABLE company_gallery DROP FOREIGN KEY FK_677962ED979B1AD6");
        $this->addSql("ALTER TABLE company_manager DROP FOREIGN KEY FK_DA763F6E979B1AD6");
        $this->addSql("ALTER TABLE deals DROP FOREIGN KEY FK_EF39849B979B1AD6");
        $this->addSql("ALTER TABLE autoservices_company DROP FOREIGN KEY FK_3EAAD222979B1AD6");
        $this->addSql("ALTER TABLE feedbacks DROP FOREIGN KEY FK_7E6C3F89979B1AD6");
        $this->addSql("ALTER TABLE user_contacts DROP FOREIGN KEY FK_D3CDF173979B1AD6");
        $this->addSql("ALTER TABLE deals_services DROP FOREIGN KEY FK_18AABA1CAEF5A6C1");
        $this->addSql("ALTER TABLE deals_auto DROP FOREIGN KEY FK_D2E53B01D55B925");
        $this->addSql("ALTER TABLE deal_auto_service DROP FOREIGN KEY FK_4900A221F60E2305");
        $this->addSql("ALTER TABLE work_deal DROP FOREIGN KEY FK_1A3D702EF60E2305");
        $this->addSql("ALTER TABLE autoservices_deal DROP FOREIGN KEY FK_A64958CAF60E2305");
        $this->addSql("ALTER TABLE feedbacks DROP FOREIGN KEY FK_7E6C3F89F60E2305");
        $this->addSql("ALTER TABLE companies DROP FOREIGN KEY FK_8244AA3A38248176");
        $this->addSql("ALTER TABLE companies DROP FOREIGN KEY FK_8244AA3A8BAC62AF");
        $this->addSql("ALTER TABLE company_dictionary_company_type_parrent DROP FOREIGN KEY FK_61B17AF5E5B3C");
        $this->addSql("ALTER TABLE company_dictionary_company_type_children DROP FOREIGN KEY FK_D4EF96CFAF5E5B3C");
        $this->addSql("ALTER TABLE company_additional_service DROP FOREIGN KEY FK_532DAE99AF5E5B3C");
        $this->addSql("ALTER TABLE company_auto_service DROP FOREIGN KEY FK_35151D26AF5E5B3C");
        $this->addSql("ALTER TABLE deals DROP FOREIGN KEY FK_EF39849BC54C8C93");
        $this->addSql("ALTER TABLE deals_services DROP FOREIGN KEY FK_18AABA1CF60E2305");
        $this->addSql("ALTER TABLE deal_auto_service DROP FOREIGN KEY FK_4900A221AF5E5B3C");
        $this->addSql("ALTER TABLE dictionaries DROP FOREIGN KEY FK_9FC78498727ACA70");
        $this->addSql("ALTER TABLE company_autoservices DROP FOREIGN KEY FK_D3F287E0979B1AD6");
        $this->addSql("ALTER TABLE company_autoservices DROP FOREIGN KEY FK_D3F287E0A723B282");
        $this->addSql("ALTER TABLE additionalservice_company DROP FOREIGN KEY FK_1B33B941CFCAAEA6");
        $this->addSql("ALTER TABLE additionalservice_company DROP FOREIGN KEY FK_1B33B941979B1AD6");
        $this->addSql("ALTER TABLE work_deal DROP FOREIGN KEY FK_1A3D702EBB3453DB");
        $this->addSql("ALTER TABLE company_type_auto_service DROP FOREIGN KEY FK_1006FC1587C14DDD");
        $this->addSql("ALTER TABLE company_type_auto_service DROP FOREIGN KEY FK_1006FC15E51E9644");
        $this->addSql("ALTER TABLE autoservices_company DROP FOREIGN KEY FK_3EAAD222A723B282");
        $this->addSql("ALTER TABLE autoservices_deal DROP FOREIGN KEY FK_A64958CAA723B282");
        $this->addSql("ALTER TABLE feedbacks DROP FOREIGN KEY FK_7E6C3F893D0770B0");
        $this->addSql("ALTER TABLE user_contacts DROP FOREIGN KEY FK_D3CDF173C54C8C93");
        $this->addSql("ALTER TABLE users DROP FOREIGN KEY FK_1483A5E98BAC62AF");
        $this->addSql("ALTER TABLE feedback_answers DROP FOREIGN KEY FK_C189E6A5D249A887");
        $this->addSql("ALTER TABLE feedback_evaluations DROP FOREIGN KEY FK_B090DCD9D249A887");
        $this->addSql("ALTER TABLE company_group_relationship DROP FOREIGN KEY FK_7F78E926FE54D947");
        $this->addSql("ALTER TABLE fos_user_user_group DROP FOREIGN KEY FK_B3C77447FE54D947");
        $this->addSql("ALTER TABLE users DROP FOREIGN KEY FK_1483A5E9A0696CB0");
        $this->addSql("ALTER TABLE company_manager DROP FOREIGN KEY FK_DA763F6EA76ED395");
        $this->addSql("ALTER TABLE feedbacks DROP FOREIGN KEY FK_7E6C3F89A76ED395");
        $this->addSql("ALTER TABLE feedback_answers DROP FOREIGN KEY FK_C189E6A57E3C61F9");
        $this->addSql("ALTER TABLE feedback_evaluations DROP FOREIGN KEY FK_B090DCD9A76ED395");
        $this->addSql("ALTER TABLE user_contacts DROP FOREIGN KEY FK_D3CDF173A76ED395");
        $this->addSql("ALTER TABLE fos_user_user_group DROP FOREIGN KEY FK_B3C77447A76ED395");
        $this->addSql("ALTER TABLE user_gallery DROP FOREIGN KEY FK_1F266630A76ED395");
        $this->addSql("DROP TABLE auto_catalog");
        $this->addSql("DROP TABLE companies");
        $this->addSql("DROP TABLE company_dictionary_company_type_parrent");
        $this->addSql("DROP TABLE company_dictionary_company_type_children");
        $this->addSql("DROP TABLE company_additional_service");
        $this->addSql("DROP TABLE company_auto_service");
        $this->addSql("DROP TABLE company_group_relationship");
        $this->addSql("DROP TABLE company_autos");
        $this->addSql("DROP TABLE company_gallery");
        $this->addSql("DROP TABLE company_manager");
        $this->addSql("DROP TABLE deals");
        $this->addSql("DROP TABLE deals_services");
        $this->addSql("DROP TABLE deals_auto");
        $this->addSql("DROP TABLE deal_auto_service");
        $this->addSql("DROP TABLE dictionaries");
        $this->addSql("DROP TABLE company_autoservices");
        $this->addSql("DROP TABLE additionalservice_company");
        $this->addSql("DROP TABLE work_deal");
        $this->addSql("DROP TABLE company_type_auto_service");
        $this->addSql("DROP TABLE autoservices_company");
        $this->addSql("DROP TABLE autoservices_deal");
        $this->addSql("DROP TABLE feedbacks");
        $this->addSql("DROP TABLE feedback_answers");
        $this->addSql("DROP TABLE feedback_evaluations");
        $this->addSql("DROP TABLE rating_points");
        $this->addSql("DROP TABLE user_contacts");
        $this->addSql("DROP TABLE groups");
        $this->addSql("DROP TABLE rating_group");
        $this->addSql("DROP TABLE users");
        $this->addSql("DROP TABLE fos_user_user_group");
        $this->addSql("DROP TABLE user_gallery");
    }
}
