<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140403153046 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE deal_additional_companies (deal_id INT NOT NULL, dictionary_id INT NOT NULL, INDEX IDX_3BCD247F60E2305 (deal_id), INDEX IDX_3BCD247AF5E5B3C (dictionary_id), PRIMARY KEY(deal_id, dictionary_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE deal_additional_companies ADD CONSTRAINT FK_3BCD247F60E2305 FOREIGN KEY (deal_id) REFERENCES deals (id)");
        $this->addSql("ALTER TABLE deal_additional_companies ADD CONSTRAINT FK_3BCD247AF5E5B3C FOREIGN KEY (dictionary_id) REFERENCES companies (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE deal_additional_companies");
    }
}
