<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130917131055 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE company_working_time ADD days_monday TINYINT(1) NOT NULL, ADD days_tuesday TINYINT(1) NOT NULL, ADD days_wednesday TINYINT(1) NOT NULL, ADD days_thursday TINYINT(1) NOT NULL, ADD days_friday TINYINT(1) NOT NULL, ADD days_saturday TINYINT(1) NOT NULL, ADD days_sunday TINYINT(1) NOT NULL, DROP days");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE company_working_time ADD days INT NOT NULL, DROP days_monday, DROP days_tuesday, DROP days_wednesday, DROP days_thursday, DROP days_friday, DROP days_saturday, DROP days_sunday");
    }
}
