<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130827152227 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE AutoServices (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, short_name VARCHAR(15) DEFAULT NULL, name VARCHAR(255) NOT NULL, position INT DEFAULT NULL, code VARCHAR(255) DEFAULT NULL, INDEX IDX_CC78F480727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("INSERT INTO AutoServices (id, parent_id, short_name, name, position, code) SELECT id, parent_id, short_name, name, position, code FROM dictionaries WHERE discr = 'auto_services'");
        $this->addSql("ALTER TABLE AutoServices ADD CONSTRAINT FK_CC78F480727ACA70 FOREIGN KEY (parent_id) REFERENCES AutoServices (id)");
        $this->addSql("ALTER TABLE company_type_auto_service DROP FOREIGN KEY FK_1006FC1587C14DDD");
        $this->addSql("ALTER TABLE company_type_auto_service ADD CONSTRAINT FK_1006FC1587C14DDD FOREIGN KEY (auto_service_id) REFERENCES AutoServices (id)");
        $this->addSql("ALTER TABLE autoservices_company DROP FOREIGN KEY FK_3EAAD222A723B282");
        $this->addSql("ALTER TABLE autoservices_company ADD CONSTRAINT FK_3EAAD222A723B282 FOREIGN KEY (autoservices_id) REFERENCES AutoServices (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE autoservices_deal DROP FOREIGN KEY FK_A64958CAA723B282");
        $this->addSql("ALTER TABLE autoservices_deal ADD CONSTRAINT FK_A64958CAA723B282 FOREIGN KEY (autoservices_id) REFERENCES AutoServices (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE company_auto_service DROP FOREIGN KEY FK_35151D26AF5E5B3C");
        $this->addSql("ALTER TABLE company_auto_service ADD CONSTRAINT FK_35151D26AF5E5B3C FOREIGN KEY (dictionary_id) REFERENCES AutoServices (id)");
        $this->addSql("ALTER TABLE companytype_autoservices DROP FOREIGN KEY FK_2D467E24A723B282");
        $this->addSql("ALTER TABLE companytype_autoservices ADD CONSTRAINT FK_2D467E24A723B282 FOREIGN KEY (autoservices_id) REFERENCES AutoServices (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE deal_auto_service DROP FOREIGN KEY FK_4900A221AF5E5B3C");
        $this->addSql("ALTER TABLE deal_auto_service ADD CONSTRAINT FK_4900A221AF5E5B3C FOREIGN KEY (dictionary_id) REFERENCES AutoServices (id)");
        $this->addSql("ALTER TABLE dictionaries DROP code");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE AutoServices DROP FOREIGN KEY FK_CC78F480727ACA70");
        $this->addSql("ALTER TABLE company_type_auto_service DROP FOREIGN KEY FK_1006FC1587C14DDD");
        $this->addSql("ALTER TABLE autoservices_company DROP FOREIGN KEY FK_3EAAD222A723B282");
        $this->addSql("ALTER TABLE autoservices_deal DROP FOREIGN KEY FK_A64958CAA723B282");
        $this->addSql("ALTER TABLE company_auto_service DROP FOREIGN KEY FK_35151D26AF5E5B3C");
        $this->addSql("ALTER TABLE companytype_autoservices DROP FOREIGN KEY FK_2D467E24A723B282");
        $this->addSql("ALTER TABLE deal_auto_service DROP FOREIGN KEY FK_4900A221AF5E5B3C");
        $this->addSql("DROP TABLE AutoServices");
        $this->addSql("ALTER TABLE autoservices_company DROP FOREIGN KEY FK_3EAAD222A723B282");
        $this->addSql("ALTER TABLE autoservices_company ADD CONSTRAINT FK_3EAAD222A723B282 FOREIGN KEY (autoservices_id) REFERENCES dictionaries (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE autoservices_deal DROP FOREIGN KEY FK_A64958CAA723B282");
        $this->addSql("ALTER TABLE autoservices_deal ADD CONSTRAINT FK_A64958CAA723B282 FOREIGN KEY (autoservices_id) REFERENCES dictionaries (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE company_auto_service DROP FOREIGN KEY FK_35151D26AF5E5B3C");
        $this->addSql("ALTER TABLE company_auto_service ADD CONSTRAINT FK_35151D26AF5E5B3C FOREIGN KEY (dictionary_id) REFERENCES dictionaries (id)");
        $this->addSql("ALTER TABLE company_type_auto_service DROP FOREIGN KEY FK_1006FC1587C14DDD");
        $this->addSql("ALTER TABLE company_type_auto_service ADD CONSTRAINT FK_1006FC1587C14DDD FOREIGN KEY (auto_service_id) REFERENCES dictionaries (id)");
        $this->addSql("ALTER TABLE companytype_autoservices DROP FOREIGN KEY FK_2D467E24A723B282");
        $this->addSql("ALTER TABLE companytype_autoservices ADD CONSTRAINT FK_2D467E24A723B282 FOREIGN KEY (autoservices_id) REFERENCES dictionaries (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE deal_auto_service DROP FOREIGN KEY FK_4900A221AF5E5B3C");
        $this->addSql("ALTER TABLE deal_auto_service ADD CONSTRAINT FK_4900A221AF5E5B3C FOREIGN KEY (dictionary_id) REFERENCES dictionaries (id)");
        $this->addSql("ALTER TABLE dictionaries ADD code VARCHAR(255) DEFAULT NULL");
    }
}
