<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130902175118 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE auto_catalog DROP FOREIGN KEY FK_31697F7D727ACA70");
        $this->addSql("ALTER TABLE company_autos DROP FOREIGN KEY FK_1F1CC491D55B925");
        $this->addSql("ALTER TABLE deals_auto DROP FOREIGN KEY FK_D2E53B01D55B925");

        $this->addSql("DROP INDEX IDX_85799BEA727ACA70 ON catalog_marks");
        $this->addSql("ALTER TABLE catalog_marks DROP parent_id");

        $this->addSql("DROP TABLE auto_catalog");


        $this->addSql("ALTER TABLE company_autos ADD CONSTRAINT FK_1F1CC491D55B925 FOREIGN KEY (auto_id) REFERENCES catalog_marks (id)");
        $this->addSql("ALTER TABLE deals DROP FOREIGN KEY FK_EF39849BC54C8C93");
        $this->addSql("ALTER TABLE deals ADD CONSTRAINT FK_EF39849BC54C8C93 FOREIGN KEY (type_id) REFERENCES deal_types (id)");

        $this->addSql("ALTER TABLE deals_auto ADD CONSTRAINT FK_D2E53B01D55B925 FOREIGN KEY (auto_id) REFERENCES catalog_marks (id)");
        $this->addSql("ALTER TABLE deal_types ADD CONSTRAINT FK_1FEF4A2C727ACA70 FOREIGN KEY (parent_id) REFERENCES deal_types (id)");


        $this->addSql("ALTER TABLE catalog_models ADD CONSTRAINT FK_56D22840727ACA70 FOREIGN KEY (parent_id) REFERENCES catalog_marks (id)");
        $this->addSql("ALTER TABLE catalog_modifications ADD CONSTRAINT FK_FD1885B727ACA70 FOREIGN KEY (parent_id) REFERENCES catalog_models (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
    }
}
