<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140527182638 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE subscriptions (id INT AUTO_INCREMENT NOT NULL, mark_id INT DEFAULT NULL, user_id INT DEFAULT NULL, type VARCHAR(100) NOT NULL, created_at DATETIME NOT NULL, updatedt_at DATETIME NOT NULL, INDEX IDX_4778A014290F12B (mark_id), INDEX IDX_4778A01A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE subscription_items (id INT AUTO_INCREMENT NOT NULL, subscription_id INT DEFAULT NULL, type VARCHAR(100) NOT NULL, item_id INT NOT NULL, `read` TINYINT(1) NOT NULL, INDEX IDX_1B26E83E9A1887DC (subscription_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE subscriptions ADD CONSTRAINT FK_4778A014290F12B FOREIGN KEY (mark_id) REFERENCES catalog_marks (id)");
        $this->addSql("ALTER TABLE subscriptions ADD CONSTRAINT FK_4778A01A76ED395 FOREIGN KEY (user_id) REFERENCES users (id)");
        $this->addSql("ALTER TABLE subscription_items ADD CONSTRAINT FK_1B26E83E9A1887DC FOREIGN KEY (subscription_id) REFERENCES subscriptions (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE subscription_items DROP FOREIGN KEY FK_1B26E83E9A1887DC");
        $this->addSql("DROP TABLE subscriptions");
        $this->addSql("DROP TABLE subscription_items");
    }
}
