<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130902152128 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE catalog_marks (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, uri VARCHAR(255) DEFAULT NULL, visible TINYINT(1) NOT NULL, icon_name VARCHAR(255) DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_85799BEA727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE catalog_models (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, uri VARCHAR(255) DEFAULT NULL, visible TINYINT(1) NOT NULL, INDEX IDX_56D22840727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE catalog_modifications (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, uri VARCHAR(255) DEFAULT NULL, visible TINYINT(1) NOT NULL, number_of_doors INT DEFAULT NULL, engine INT DEFAULT NULL, power INT DEFAULT NULL, full_speed INT DEFAULT NULL, body_type VARCHAR(255) DEFAULT NULL, start_of_production VARCHAR(255) DEFAULT NULL, closing_of_production VARCHAR(255) DEFAULT NULL, INDEX IDX_FD1885B727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("INSERT INTO catalog_marks (id, parent_id, name, uri, visible, icon_name, updated_at) SELECT id, parent_id, name, uri, visible, icon_name, updated_at FROM auto_catalog WHERE discr = 'mark'");
        $this->addSql("INSERT INTO catalog_models (id, parent_id, name, uri, visible) SELECT id, parent_id, name, uri, visible FROM auto_catalog WHERE discr = 'model'");
        $this->addSql("INSERT INTO catalog_modifications (id, parent_id, name, uri, visible, number_of_doors, engine, power, full_speed, body_type, start_of_production, closing_of_production) SELECT id, parent_id, name, uri, visible, number_of_doors, engine, power, full_speed, body_type, start_of_production, closing_of_production FROM auto_catalog WHERE discr = 'modification'");
        $this->addSql("ALTER TABLE catalog_marks ADD CONSTRAINT FK_85799BEA727ACA70 FOREIGN KEY (parent_id) REFERENCES catalog_marks (id)");
        $this->addSql("ALTER TABLE catalog_models ADD CONSTRAINT FK_56D22840727ACA70 FOREIGN KEY (parent_id) REFERENCES catalog_models (id)");
        $this->addSql("ALTER TABLE catalog_modifications ADD CONSTRAINT FK_FD1885B727ACA70 FOREIGN KEY (parent_id) REFERENCES catalog_modifications (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE catalog_marks DROP FOREIGN KEY FK_85799BEA727ACA70");
        $this->addSql("ALTER TABLE catalog_models DROP FOREIGN KEY FK_56D22840727ACA70");
        $this->addSql("ALTER TABLE catalog_modifications DROP FOREIGN KEY FK_FD1885B727ACA70");
        $this->addSql("DROP TABLE catalog_marks");
        $this->addSql("DROP TABLE catalog_models");
        $this->addSql("DROP TABLE catalog_modifications");
    }
}
