<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130926130001 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE company_type_auto_service");
        $this->addSql("ALTER TABLE auto_services ADD company_type_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE auto_services ADD CONSTRAINT FK_B5147D96E51E9644 FOREIGN KEY (company_type_id) REFERENCES company_types (id)");
        $this->addSql("CREATE INDEX IDX_B5147D96E51E9644 ON auto_services (company_type_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE company_type_auto_service (auto_service_id INT NOT NULL, company_type_id INT NOT NULL, INDEX IDX_1006FC1587C14DDD (auto_service_id), INDEX IDX_1006FC15E51E9644 (company_type_id), PRIMARY KEY(auto_service_id, company_type_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE company_type_auto_service ADD CONSTRAINT FK_1006FC1587C14DDD FOREIGN KEY (auto_service_id) REFERENCES auto_services (id)");
        $this->addSql("ALTER TABLE company_type_auto_service ADD CONSTRAINT FK_1006FC15E51E9644 FOREIGN KEY (company_type_id) REFERENCES company_types (id)");
        $this->addSql("ALTER TABLE auto_services DROP FOREIGN KEY FK_B5147D96E51E9644");
        $this->addSql("DROP INDEX IDX_B5147D96E51E9644 ON auto_services");
        $this->addSql("ALTER TABLE auto_services DROP company_type_id");
    }
}
