<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130910160623 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE company_specializations DROP INDEX UNIQ_F906A4C2C54C8C93, ADD INDEX IDX_F906A4C2C54C8C93 (type_id)");
        $this->addSql("ALTER TABLE company_specializations DROP INDEX UNIQ_F906A4C241931DC0, ADD INDEX IDX_F906A4C241931DC0 (subType_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE company_specializations DROP INDEX IDX_F906A4C2C54C8C93, ADD UNIQUE INDEX UNIQ_F906A4C2C54C8C93 (type_id)");
        $this->addSql("ALTER TABLE company_specializations DROP INDEX IDX_F906A4C241931DC0, ADD UNIQUE INDEX UNIQ_F906A4C241931DC0 (subType_id)");
    }
}
