<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140505220123 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE user_cars ADD year INT NOT NULL, ADD engineType VARCHAR(255) DEFAULT NULL, ADD engineModel VARCHAR(255) DEFAULT NULL, ADD engineVolume INT DEFAULT NULL, ADD enginePower INT DEFAULT NULL, ADD fuelTypes LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', ADD wheelType VARCHAR(255) DEFAULT NULL, ADD bodyType VARCHAR(255) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE user_cars DROP year, DROP engineType, DROP engineModel, DROP engineVolume, DROP enginePower, DROP fuelTypes, DROP wheelType, DROP bodyType");
    }
}
