<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130913123619 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE company_types CHANGE icon_name_small icon_name_map_selected VARCHAR(255) DEFAULT NULL, CHANGE icon_name_large icon_name_company_card VARCHAR(255) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE company_types ADD icon_name_small VARCHAR(255) DEFAULT NULL, ADD icon_name_large VARCHAR(255) DEFAULT NULL, DROP icon_name_map_selected, DROP icon_name_company_card");
    }
}
