<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130826171618 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE Country (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, short_name VARCHAR(15) DEFAULT NULL, name VARCHAR(255) NOT NULL, position INT DEFAULT NULL, icon_name VARCHAR(255) DEFAULT NULL, image_name VARCHAR(255) DEFAULT NULL, updated_at DATETIME DEFAULT NULL, gps VARCHAR(255) DEFAULT NULL, INDEX IDX_9CCEF0FA727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE Country ADD CONSTRAINT FK_9CCEF0FA727ACA70 FOREIGN KEY (parent_id) REFERENCES Country (id)");
        $this->addSQL("INSERT INTO Country (id, parent_id, short_name, name, position, icon_name, image_name, updated_at, gps) SELECT id, parent_id, short_name, name, position, icon_name, image_name, updated_at, gps FROM dictionaries WHERE discr='country'");
        $this->addSql("ALTER TABLE companies DROP FOREIGN KEY FK_8244AA3A8BAC62AF");
        $this->addSql("ALTER TABLE companies ADD CONSTRAINT FK_8244AA3A8BAC62AF FOREIGN KEY (city_id) REFERENCES Country (id)");
        $this->addSql("ALTER TABLE dictionaries DROP icon_name, DROP image_name, DROP gps");
        $this->addSql("ALTER TABLE users DROP FOREIGN KEY FK_1483A5E98BAC62AF");
        $this->addSql("ALTER TABLE users ADD CONSTRAINT FK_1483A5E98BAC62AF FOREIGN KEY (city_id) REFERENCES Country (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE companies DROP FOREIGN KEY FK_8244AA3A8BAC62AF");
        $this->addSql("ALTER TABLE Country DROP FOREIGN KEY FK_9CCEF0FA727ACA70");
        $this->addSql("ALTER TABLE users DROP FOREIGN KEY FK_1483A5E98BAC62AF");
        $this->addSql("DROP TABLE Country");
        $this->addSql("ALTER TABLE companies DROP FOREIGN KEY FK_8244AA3A8BAC62AF");
        $this->addSql("ALTER TABLE companies ADD CONSTRAINT FK_8244AA3A8BAC62AF FOREIGN KEY (city_id) REFERENCES dictionaries (id)");
        $this->addSql("ALTER TABLE dictionaries ADD icon_name VARCHAR(255) DEFAULT NULL, ADD image_name VARCHAR(255) DEFAULT NULL, ADD gps VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE users DROP FOREIGN KEY FK_1483A5E98BAC62AF");
        $this->addSql("ALTER TABLE users ADD CONSTRAINT FK_1483A5E98BAC62AF FOREIGN KEY (city_id) REFERENCES dictionaries (id)");
    }
}
