<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130911133538 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE company_specializations DROP INDEX UNIQ_F906A4C2979B1AD6, ADD INDEX IDX_F906A4C2979B1AD6 (company_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE company_specializations DROP INDEX IDX_F906A4C2979B1AD6, ADD UNIQUE INDEX UNIQ_F906A4C2979B1AD6 (company_id)");
    }
}
