<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130826143718 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE company_contacts (id INT AUTO_INCREMENT NOT NULL, company_id INT DEFAULT NULL, type_id INT DEFAULT NULL, value VARCHAR(255) NOT NULL, INDEX IDX_2BD7001E979B1AD6 (company_id), INDEX IDX_2BD7001EC54C8C93 (type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE company_contacts ADD CONSTRAINT FK_2BD7001E979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id)");
        $this->addSql("ALTER TABLE company_contacts ADD CONSTRAINT FK_2BD7001EC54C8C93 FOREIGN KEY (type_id) REFERENCES dictionaries (id)");
        $this->addSql("INSERT INTO company_contacts (company_id, type_id, value) SELECT company_id, type_id, value FROM user_contacts WHERE company_id > 0");
        $this->addSql("ALTER TABLE user_contacts DROP FOREIGN KEY FK_D3CDF173979B1AD6");
        $this->addSql("DROP INDEX IDX_D3CDF173979B1AD6 ON user_contacts");
        $this->addSql("ALTER TABLE user_contacts DROP company_id");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE company_contacts");
        $this->addSql("ALTER TABLE user_contacts ADD company_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE user_contacts ADD CONSTRAINT FK_D3CDF173979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id)");
        $this->addSql("CREATE INDEX IDX_D3CDF173979B1AD6 ON user_contacts (company_id)");
    }
}
