<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131003154605 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE INDEX companies_search_idx ON companies (name, full_name, slogan)");
        $this->addSql("CREATE INDEX company_types_search_idx ON company_types (name)");
        $this->addSql("CREATE INDEX deals_search_idx ON deals (name, terms)");
        $this->addSql("CREATE INDEX marks_search_idx ON catalog_marks (name)");
        $this->addSql("CREATE INDEX models_search_idx ON catalog_models (name)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP INDEX marks_search_idx ON catalog_marks");
        $this->addSql("DROP INDEX models_search_idx ON catalog_models");
        $this->addSql("DROP INDEX companies_search_idx ON companies");
        $this->addSql("DROP INDEX company_types_search_idx ON company_types");
        $this->addSql("DROP INDEX deals_search_idx ON deals");
    }
}
