<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130723163801 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE company_autos DROP FOREIGN KEY FK_1F1CC49979B1AD6");
        $this->addSql("ALTER TABLE company_autos DROP FOREIGN KEY FK_1F1CC491D55B925");
        $this->addSql("ALTER TABLE company_autos DROP PRIMARY KEY");
        $this->addSql("ALTER TABLE company_autos ADD CONSTRAINT FK_1F1CC49979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id)");
        $this->addSql("ALTER TABLE company_autos ADD CONSTRAINT FK_1F1CC491D55B925 FOREIGN KEY (auto_id) REFERENCES auto_catalog (id)");
        $this->addSql("ALTER TABLE company_autos ADD PRIMARY KEY (company_id, auto_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE company_autos DROP FOREIGN KEY FK_1F1CC49979B1AD6");
        $this->addSql("ALTER TABLE company_autos DROP FOREIGN KEY FK_1F1CC491D55B925");
        $this->addSql("ALTER TABLE company_autos DROP PRIMARY KEY");
        $this->addSql("ALTER TABLE company_autos ADD CONSTRAINT FK_1F1CC49979B1AD6 FOREIGN KEY (company_id) REFERENCES auto_catalog (id)");
        $this->addSql("ALTER TABLE company_autos ADD CONSTRAINT FK_1F1CC491D55B925 FOREIGN KEY (auto_id) REFERENCES companies (id)");
        $this->addSql("ALTER TABLE company_autos ADD PRIMARY KEY (auto_id, company_id)");
    }
}
