<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130812182145 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE companies CHANGE hour_price hour_price INT DEFAULT NULL");
        $this->addSql("ALTER TABLE company_gallery CHANGE visible visible TINYINT(1) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE companies CHANGE hour_price hour_price VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE company_gallery CHANGE visible visible TINYINT(1) NOT NULL");
    }
}
