<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130805125710 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE companytype_autoservices (companytype_id INT NOT NULL, autoservices_id INT NOT NULL, INDEX IDX_2D467E241E00F65 (companytype_id), INDEX IDX_2D467E24A723B282 (autoservices_id), PRIMARY KEY(companytype_id, autoservices_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE companytype_autoservices ADD CONSTRAINT FK_2D467E241E00F65 FOREIGN KEY (companytype_id) REFERENCES dictionaries (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE companytype_autoservices ADD CONSTRAINT FK_2D467E24A723B282 FOREIGN KEY (autoservices_id) REFERENCES dictionaries (id) ON DELETE CASCADE");
        $this->addSql("DROP TABLE company_autoservices");
        $this->addSql("ALTER TABLE additionalservice_company DROP FOREIGN KEY FK_1B33B941979B1AD6");
        $this->addSql("ALTER TABLE additionalservice_company ADD CONSTRAINT FK_1B33B941979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE company_autoservices (company_id INT NOT NULL, autoservices_id INT NOT NULL, INDEX IDX_D3F287E0979B1AD6 (company_id), INDEX IDX_D3F287E0A723B282 (autoservices_id), PRIMARY KEY(company_id, autoservices_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE company_autoservices ADD CONSTRAINT FK_D3F287E0979B1AD6 FOREIGN KEY (company_id) REFERENCES dictionaries (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE company_autoservices ADD CONSTRAINT FK_D3F287E0A723B282 FOREIGN KEY (autoservices_id) REFERENCES dictionaries (id) ON DELETE CASCADE");
        $this->addSql("DROP TABLE companytype_autoservices");
        $this->addSql("ALTER TABLE additionalservice_company DROP FOREIGN KEY FK_1B33B941979B1AD6");
        $this->addSql("ALTER TABLE additionalservice_company ADD CONSTRAINT FK_1B33B941979B1AD6 FOREIGN KEY (company_id) REFERENCES dictionaries (id) ON DELETE CASCADE");
    }
}
