<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130913130124 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("DROP TABLE company_working_time");
        $this->addSql("CREATE TABLE company_working_time (id INT AUTO_INCREMENT NOT NULL, company_id INT DEFAULT NULL, `from` TIME NOT NULL, till TIME NOT NULL, days INT NOT NULL, INDEX IDX_CF23E071979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE company_working_time ADD CONSTRAINT FK_CF23E071979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE company_working_time");
    }
}
