<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130930140630 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE company_services (id INT AUTO_INCREMENT NOT NULL, service_id INT DEFAULT NULL, specialization_id INT DEFAULT NULL, parent_id INT DEFAULT NULL, INDEX IDX_6BA5F404ED5CA9E6 (service_id), INDEX IDX_6BA5F404FA846217 (specialization_id), INDEX IDX_6BA5F404727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE company_services ADD CONSTRAINT FK_6BA5F404ED5CA9E6 FOREIGN KEY (service_id) REFERENCES auto_services (id)");
        $this->addSql("ALTER TABLE company_services ADD CONSTRAINT FK_6BA5F404FA846217 FOREIGN KEY (specialization_id) REFERENCES company_specializations (id)");
        $this->addSql("ALTER TABLE company_services ADD CONSTRAINT FK_6BA5F404727ACA70 FOREIGN KEY (parent_id) REFERENCES company_services (id)");
        $this->addSql("ALTER TABLE auto_services CHANGE company_type_id company_type_id INT NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE company_services DROP FOREIGN KEY FK_6BA5F404727ACA70");
        $this->addSql("DROP TABLE company_services");
        $this->addSql("ALTER TABLE auto_services CHANGE company_type_id company_type_id INT DEFAULT NULL");
    }
}
